### ISSUE TITLE
Color ID panel missing

### ISSUE THREAD

**Issue by iillya** [franMarz/TexTools-Blender#225] opened 2024-08-21 03:54 UTC
Color ID panel missing
blender 4.2.0
TexTools  1.6.1
![image](https://github.com/user-attachments/assets/15756716-f939-4ac1-b4c1-80af9758461d)

**Comment by franMarz** [comment] 2024-08-22 09:41
This is a duplicate of the already solved #217 issue, please install [the latest version of TexTools from master](https://github.com/franMarz/TexTools-Blender/archive/refs/heads/master.zip)

**Closed as completed by franMarz** 2024-08-22 09:41 UTC
