### ISSUE TITLE
AO Bake not capturing surface detail

### ISSUE THREAD

**Issue by Ulazygit** [franMarz/TexTools-Blender#58] opened 2020-11-29 23:51 UTC
When using Blender's own AO bake for cycles (with conventional node setup) one gets surface detail as part of the bake. Using this plugin however provides no surface detail for the AO bake and thus shades the surfaces as though flat.
![AO detail](https://user-images.githubusercontent.com/60723284/100556830-eef12480-329c-11eb-8bfb-b78a53ce38ba.png)

The above is an example of the desired level of detail from Blender's integrated AO bake with procedurally generated textures.

On the other hand, this is the undesirable outcome from the plugin where such detail is lost.

![undesired](https://user-images.githubusercontent.com/60723284/100556939-b736ac80-329d-11eb-8d03-6bba7ec0e8ef.JPG)

**Comment by franMarz** [comment] 2020-12-07 18:50
This should be related to how the blender Python API manage the baking of AO, because if you use the following script with an image active on the object's shader:
import bpy
bpy.ops.object.bake(type='AO')
You'll get the same smoothed result.
You better report this in developer.blender.org?

**Comment by franMarz** [comment] 2020-12-15 02:00
Closing now due to inactivity, you can reopen this task if you find out that this addon is actually responsible of the issue.

**Comment by franMarz** [comment] 2020-12-20 08:39
The addon is the culprit. I don't understand why the simple script I posted delivered the same result. The issue is already fixed on my side, but I want to enhance the code more before sharing it. Reopening.

**Comment by franMarz** [comment] 2020-12-23 10:03
Fixed in TexTools 1.4.1, download and install the latest release: [https://github.com/SavMartin/TexTools-Blender/releases/download/v1.4.1/TexTools_Blender_1_4_1.zip](https://github.com/SavMartin/TexTools-Blender/releases/download/v1.4.1/TexTools_Blender_1_4_1.zip)

**Closed as completed by franMarz** 2020-12-23 10:03 UTC
Labels: bug
