### ISSUE TITLE
Blender does not quit when rendering from command line

### ISSUE THREAD

**Issue by TheShouting** [franMarz/TexTools-Blender#120] opened 2021-12-29 16:27 UTC
When trying to render a project from the command line, blender only shuts down by killing it with Ctrl+C. I narrowed it down to TexTools by enabling and reenabling my list of plugins.
This causes issues when trying to batch render from batch script or batch rendering addon as they all seem to utilize the command line. I'd have to disable TextTools before I render each time for it to work properly.

System:
```
Windows 10
Blender 3.0 Release
```
Using latest 1.4.4 version from master repository. I do not see any TextTools errors in the console output.

**Comment by SavMartin** [comment] 2022-01-14 20:57
Disable all other plugins you have, and just leave Textools and try..

**Comment by levilansing** [comment] 2022-01-30 20:50
I suspect this is my problem as well. As soon as I upgraded to 1.4.4, Unity (the game engine) hangs every time it tries to import ANY blender file (Unity uses blender through the command line to convert blend files into FBX data it can work with). If I disable the TexTools plugin, it works fine. If I downgrade to 1.4.3, it works fine.

When I open my task manager and expand Unity, I see blender running as a child process of Unity but not using any CPU.

I'm using blender 2.93.7

**Comment by franMarz** [comment] 2022-02-01 21:07
Fisrt, are you talking about the latest release or the current master? Because both are 1.4.4.
If you are talking about master, I would ask any of you for a difficult investigation: Could you try any of the addons that use the [3dninjas library](https://github.com/3dninjas/3dn-bip) and see if a similar error happens? Because, apart from that, I don't see how any other change made to the code since 1.4.3 can be responsible for such a behaviour.

**Comment by levilansing** [comment] 2022-02-12 00:25
I *think* I tried both, but using the 1.4.4 release download for the repro steps:

1. Create a python file called `export.py` and with the following:
```
import bpy
import sys

bpy.ops.export_scene.fbx(filepath='exported.fbx', axis_forward='-Z', axis_up='Y')
```
2. Install and enable v1.4.4 of TexTools, and save preferences
3. from powershell, run the following command from the folder with export.py and a sample blender file:
```
& "C:\Program Files\Blender Foundation\Blender 2.93\blender.exe" cube.blend --background --python export.py
```
4. notice the console reads "export finished in ..." but it never exits

I did some experimentation and tried the only plugin I could find that used the 3DN BIP library, Kit Ops. Downloaded their latest free version and it did not have the same issue, but noticed it was using version `1.0.8` of 3DN BIP and TexTools is using `1.0.9`.

First I tried "upgrading" Kit Ops to use `1.0.9` by replacing the contents of 3DN BIP inside the plugin, and i don't know if it worked or not because I saw some errors in the console, but I couldn't repro the issue.

So next I tried the opposite, and DOWNGRADED TexTools to `1.0.8` by replacing the contents of `t3dn_bip/` with files from `1.0.8` and the plugin seems to work fine (with only some warning about Pillow not being installed) and I can no longer reproduce this issue with the above steps.

So I think you're right, the problem lies somewhere in 3DN BIP, but a solution might just be to downgrade 3DN BIP if that's acceptable to you.

**Comment by franMarz** [comment] 2022-02-12 14:38
Brilliant, thank you so much! I'll look into downgrading the 3DN BIP implementation as you suggest.

**Comment by paulgolter** [comment] 2022-02-14 15:23
Hey a colleague has the same problem. 

When `TexTools` is enabled something seems to prevent Blender from auto closing when starting it in background using: 

`/path/to/blender --background`

**Comment by franMarz** [comment] 2022-02-16 02:25
Please try latest master. Hopefully this issue is solved now.

**Comment by levilansing** [comment] 2022-02-28 00:31
Master is working for me, thanks!

**Comment by franMarz** [comment] 2022-02-28 03:42
It seems that from now on this won't be a problem. Closing.

**Closed as completed by franMarz** 2022-02-28 03:42 UTC
Labels: question
