### ISSUE TITLE
Baking material ids for multiple objects, reuses colors for different materials

### ISSUE THREAD

**Issue by MHAbrah** [franMarz/TexTools-Blender#25] opened 2020-06-24 21:46 UTC
When I select multiple high-poly (suffix "_high") and multiple matching low-poly (suffix "_low") objects and want to use the materials assigned to the high-poly to bake a material id (using the low-poly's UVs). I almost get what I expect:

The material ID texture is genreated and matches the UVs but the colors are reused for different materials. It seems that the colors are assigned based on material slots, not materials e.i. the first material slot of one high poly is red and the first slot of another high poly is also red. These are in my case not the same material just the same index number for the two separate objects.

Is this intended behavior or a bug?

**Comment by ketulrudani** [comment] 2020-10-13 21:12
I am having same problem

**Comment by franMarz** [comment] 2020-12-15 21:21
It works as intended: [http://renderhjs.net/textools/blender/](http://renderhjs.net/textools/blender/) Look for "Material ID"
It should be possible to change it though, I think is not even necessary to provide an option, so that going for "color by material" as default is the expected and only desirable behaviour. Right?

**Comment by franMarz** [comment] 2020-12-17 20:24
You can test the future Material ID baking by installing this upcoming version of TexTools: [https://github.com/SavMartin/TexTools-Blender/archive/material-ID-fixes.zip](https://github.com/SavMartin/TexTools-Blender/archive/material-ID-fixes.zip). Probably no bugs free for now, please inform on this issue post about any problem you find.

**Comment by franMarz** [comment] 2020-12-19 07:41
Fixed in the latest release.

**Closed as completed by franMarz** 2020-12-19 07:41 UTC

**Comment by ketulrudani** [comment] 2020-12-19 08:19
Okay, thanks
