### ISSUE TITLE
Color ID - Wrong Labels and Empty Material Slots After Conversion

### ISSUE THREAD

**Issue by zaha** [franMarz/TexTools-Blender#83] opened 2021-06-10 19:24 UTC
I think there’s a copy/paste error on the button labels for “Select by color”:

![image](https://user-images.githubusercontent.com/1721211/121584790-27cf3a80-ca32-11eb-8d43-643538030c6b.png)

And after I converted the Material IDs to Vertex Color IDs and add another Material Color ID, there are empty Material slots for every Material Color ID I had before:

![image](https://user-images.githubusercontent.com/1721211/121584824-2ef64880-ca32-11eb-9dfe-ddaf20c81c03.png)

**Comment by franMarz** [comment] 2021-06-11 06:58
I can't reproduce it, I get the previous materials reassigned to the slots plus the new slot and material. Would you mind recording the process and upload the video/gif here?

**Comment by zaha** [comment] 2021-06-12 14:34
Sure thing, here you go:

![2021-06-12_FjrPN5OFoq](https://user-images.githubusercontent.com/1721211/121779468-173ad380-cb9c-11eb-962e-b1a728326a5e.gif)

**Comment by franMarz** [comment] 2021-06-13 04:21
Ok, It seems that I was assigning the palette with the first dropdown or the number next to it before, now I see what is happening.
This is normal considering how each color is indexed to a ordered slot. I can make that every slot get its corresponding colored material even though it is not assigned to any face. And even better it would be if the material assignment is not lost every time a conversion is performed. If you want to clear the assignment, you have a button just for doing that in the panel anyway.

**Comment by franMarz** [comment] 2021-06-13 09:01
There is a problem when populating the slots with materials: all faces without a material assigned will use the material in the slot 0 as soon as any material is assigned to any face. You can test it yourself:

[op_color_assign.zip](https://github.com/SavMartin/TexTools-Blender/files/6643584/op_color_assign.zip)

**Comment by franMarz** [comment] 2021-06-13 09:16
This needs a better rethinking. Or leave it as it is, or change it so only assigned materials create a slot in the object, but I don't think that will follow the original idea of the tool and a rewrite of all color ID related modules would be necessary.
The question is: Is there any problem with having empty material slots in an object which you are using this destructive color IDF workflow at?

**Comment by zaha** [comment] 2021-06-13 10:07
> Is there any problem with having empty material slots in an object which you are using this destructive color IDF workflow at?

No, nothing serious. I usually delete them by hand, so it's just a slight nuisance. And tbh, if the dropdown as suggested in #82 is implemented then there is no need for me to get my vertex color IDs via materials in the first place, making this a non-issue for me.

Thanks for the investigatiion anyway, appreciate it!

**Closed as completed** 2021-06-13 16:54 UTC
Labels: enhancement
